CREATE DATABASE IF NOT EXISTS wantedlab;
GRANT ALL PRIVILEGES ON wantedlab.* TO 'dev'@'%';
GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE, REFERENCES ON *.* TO 'dev'@'%';
FLUSH PRIVILEGES;